on: [push] # push 代码时触发
jobs: 
    deploy: 
        runs-on: ubuntu-latest
        name: Tencent Cloudbase Github Action Example
        steps: 
        - name: Checkout
          uses: actions/checkout@v2
        # 使用云开发 Github Action 部署
        - name: Deploy static to Tencent CloudBase
          id: deployStatic
          uses: TencentCloudBase/cloudbase-action@v1.1.1
          with: 
            # 云开发的访问密钥 secretId 和 secretKey
            secretId: ${{ AKIDud8PQCiz1pOincCWbR1MRzIMAj38xXsz }}
            secretKey: ${{ uZy83i8JEuKVQ6WhcIitrb5KK4YnmW0H }}
            # 云开发的环境id
            envId: ${{ calvinhaynes-blog-7e7e1n8099c15d }}
            # Github 项目静态文件的路径
            staticSrcPath: docs
